### ISSUE TITLE
UI with graphs and large current-value text

### ISSUE THREAD

**Issue by jkoberg** [jkoberg/splitvent#2]
Display the stream of readings in real

Low latency is ideal - consider single-process solutions.  The device interface is very simple and conforms to standard unix APIs; it can easily be ported to another language instead of running multiple processes.

**Comment by JanCBrammer** [comment]
Consider using [pyqtgraph](https://github.com/pyqtgraph/pyqtgraph) for plotting the signal with low latency in real-time. Here's a nice [example](https://github.com/eegsynth/eegsynth/blob/master/module/plotsignal/plotsignal.py). pyqtgraph widgets can be incorporated in a [PyQt5](https://www.riverbankcomputing.com/static/Docs/PyQt5/) (Python implementation of the [Qt library](https://www.qt.io/)) UI in case more elaborate user interactions are required (i.e., text inputs, file dialogues etc.).

**Comment by jkoberg** [comment]
Implemented with Pygame for now.  Can QT run on the console?
